travis:
  secure:
    BINSTAR_TOKEN: RZ7VmmPFq1um6ULcTtaEVMBFiM+Q0CeQ49aS7fn0hFBy6QmylG5jKIPUSMOLsmzfHZatxNlOCq6qvv8QU/TIKg8hHHIWPMWhilJ03PXXX4PpiqDnN8U1JTIhy8DxFTSyL3f0tJZlXmApZgzA/ZZx2S0CGpQ9Qa8Lp6YYvfa8DaYysvxq975E+VhM8bwstURg8pzKW/4cOdj4up9BKL0agyNGHW9tiAfpmA0LmITi3tu9EnwMkXh03veMRlJBVbNk0YIwz5RDYQqkZ6Q56CUWxHCAND9sTAY20TpGm4jVSYyS3xGaiKmswfAMWIU3Tb4w/swSAO0lUrsdZMsIILpqszNF1Amtmzo8ogzjTJU4VoT+Fq7U98eeWQkGWZiK681IZ58DOKexyQT+gSW24IGbQkoFB5Q03Q9d+R0kbsjOodWY/kSBnGy9K3ifm81PTnwsw9kW0BreRGv+EkaNyItitTNdZlIQsPOgDKMvmVk01Rb4D+ahTwSkIakZK7lktlFTTeFdp2+95vHqjCR5X/r1etwxi3YsyGh9cgRnMndm0dsam8TDQ1zYq7SqE1nnQy4Ul4e7G5bNUzeH14nheo8A9cfNF55ugQDlLwouMQ0lTwgO3X8E2MvAju0zQcNrxbYOXIi/s5ScM0Niq+wnT1ocH3XSUE8Kg4wEmm6YuvITpQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
